// src/data/timelineData.js
export const timelineData = [
  {
    id: 1,
    type: 'record',
    title: 'Birth Certificate Uploaded',
    description: 'Patient uploaded official birth certificate.',
    date: '2000-01-15',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 2,
    type: 'record',
    title: 'Polio Vaccination Certificate',
    description: 'Certificate uploaded after polio vaccine administered.',
    date: '2000-04-10',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 3,
    type: 'record',
    title: 'Childhood Immunization Record',
    description: 'Includes MMR, DPT, and Hepatitis B vaccines.',
    date: '2004-08-22',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 4,
    type: 'record',
    title: 'Aadhar Card Uploaded',
    description: 'Patient uploaded Aadhar Card for identity verification.',
    date: '2015-06-30',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 5,
    type: 'record',
    title: 'COVID-19 Vaccination Certificate',
    description: 'Patient uploaded COVID-19 Vaccination Certificate.',
    date: '2021-04-22',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 6,
    type: 'diagnosis',
    title: 'Diabetes Checkup',
    description: 'Routine diabetes screening.',
    date: '2023-09-18',
    doctor: 'Dr. Meera Deshmukh',
    hospital: 'Ruby Hall Clinic, Pune',
    notes: 'Fasting glucose: 120 mg/dL. No medication required yet.',
    topic: 'Type 2 Diabetes Screening',
  },
  {
    id: 7,
    type: 'prescription',
    title: 'Vitamin D3 Supplement',
    description: 'Cholecalciferol 60,000 IU once a week for 8 weeks.',
    date: '2023-09-19',
    medicines: [
      {
        name: 'Cholecalciferol',
        dosage: '60,000 IU',
        frequency: 'Once a week',
        duration: '8 weeks',
      },
    ],
    instructions: 'Take with milk after meals.',
  },
  {
    id: 8,
    type: 'diagnosis',
    title: 'Blood Test Results',
    description: 'Annual blood work review.',
    date: '2023-09-22',
    doctor: 'Dr. Aditya Rao',
    hospital: 'Jehangir Hospital, Pune',
    notes: 'Hemoglobin: 10.5 g/dL. Advised iron-rich diet and supplements.',
    topic: 'General Blood Profile',
  },
  {
    id: 9,
    type: 'record',
    title: 'MRI Scan Report Uploaded',
    description: 'Brain MRI uploaded for neurologist consultation.',
    date: '2023-09-23',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 10,
    type: 'prescription',
    title: 'Prescribed: Paracetamol',
    description: '500mg, 2 times a day after meals for 3 days.',
    date: '2023-09-25',
    medicines: [
      {
        name: 'Paracetamol',
        dosage: '500mg',
        frequency: '2 times/day',
        duration: '3 days',
      },
    ],
    instructions: 'Do not exceed 4g per day.',
  },
  {
    id: 11,
    type: 'diagnosis',
    title: 'High Blood Pressure Detected',
    description: 'Routine health check.',
    date: '2023-09-27',
    doctor: 'Dr. Rakesh Patil',
    hospital: 'Apollo Clinic, Pune',
    notes: 'BP recorded at 150/95. Lifestyle changes and monitoring advised.',
    topic: 'Hypertension Stage 1',
  },
  {
    id: 12,
    type: 'prescription',
    title: 'BP Medication',
    description: 'Amlodipine 5mg once daily after breakfast.',
    date: '2023-09-28',
    medicines: [
      {
        name: 'Amlodipine',
        dosage: '5mg',
        frequency: 'Once daily',
        duration: '30 days',
      },
    ],
    instructions: 'Take daily at the same time.',
  },
  {
    id: 13,
    type: 'record',
    title: 'Allergy Report Uploaded',
    description: 'Allergy test confirms sensitivity to dust and pollen.',
    date: '2023-09-29',
    fileUrl: '../assets/hello.pdf',
  },
  {
    id: 14,
    type: 'diagnosis',
    title: 'Seasonal Flu Diagnosed',
    description: 'Consulted for cold, cough, and fever.',
    date: '2023-10-01',
    doctor: 'Dr. Sneha Kulkarni',
    hospital: 'Noble Hospital, Pune',
    notes: 'Flu confirmed. Advised rest and hydration.',
    topic: 'Viral Infection - Seasonal Influenza',
  },
  {
    id: 15,
    type: 'prescription',
    title: 'Anti-allergy Medication',
    description: 'Loratadine 10mg once daily.',
    date: '2023-10-02',
    medicines: [
      {
        name: 'Loratadine',
        dosage: '10mg',
        frequency: 'Once daily',
        duration: '7 days',
      },
    ],
    instructions: 'Take in the evening to avoid drowsiness at work.',
  },
];
